### ISSUE TITLE
Przeczytać podstawowy poradnik Unreal Engine

### ISSUE THREAD

**Issue by dofranko** [dofranko/Fists-of-Snake-3D#2]
https://learn.unrealengine.com/home/dashboard
https://learn.unrealengine.com/home/library

-Nauczyć się poruszania po oprogramowaniu do silnika

**Comment by dofranko** [comment]
![obraz](https://user-images.githubusercontent.com/56605429/95874042-c6ef4580-0d70-11eb-99bb-9ab847b4dd41.png)
Done 😀

**Comment by adbednarz** [comment]
![Untitled](https://user-images.githubusercontent.com/25796287/95922982-c37dad80-0db4-11eb-8104-b8c3afac38d6.png)
Done :)

**Comment by ghost** [comment]
![obraz_2020-11-18_180834](https://user-images.githubusercontent.com/56612078/99562991-11e02680-29c9-11eb-8b20-2271aaccdc3b.png)
