### ISSUE TITLE
Crash całego edytora/silnika po podniesieniu przedmiotu

### ISSUE THREAD

**Issue by dofranko** [dofranko/Fists-of-Snake-3D#23]
Naprawić błąd.
Jak odtworzyć:
Właczyć rozgrywkę. Nacisnąć 'G'. Podejść do broni. <<CRASH>

**Comment by adbednarz** [comment]
Diabeł tkwi w szczegółach, tak było i w tym przypadku. Jednak błąd udało się w miarę bezboleśnie usunąć.
