### ISSUE TITLE
Zła rotacja broni względem gracza podczas zmiany broni

### ISSUE THREAD

**Issue by dofranko** [dofranko/Fists-of-Snake-3D#24]
Jw.
Śmieszny, wizualny bug.
![obraz](https://user-images.githubusercontent.com/56605429/100636904-82c10000-3332-11eb-8943-ea6598d69130.png)

**Comment by adbednarz** [comment]
![mem](https://user-images.githubusercontent.com/25796287/102030411-03f8a800-3db3-11eb-8511-2ef34f51f058.jpg)
