### ISSUE TITLE
Przeczytać poradnik odnośnie blueprintów

### ISSUE THREAD

**Issue by dofranko** [dofranko/Fists-of-Snake-3D#3]
https://learn.unrealengine.com/home/dashboard
https://learn.unrealengine.com/home/library

-Nauczyć się tzw. "blueprintów"

**Comment by adbednarz** [comment]
![kurs2](https://user-images.githubusercontent.com/25796287/99198170-16bd9400-2797-11eb-9bc1-c25fdbd6a43e.png)

**Comment by dofranko** [comment]
![obraz](https://user-images.githubusercontent.com/56605429/99284702-df062900-2836-11eb-9745-679eb06ad4d1.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/56612078/99563207-4f44b400-29c9-11eb-8118-c638099a9f2d.png)
